# Generated by Django 6.0.3 on 2026-03-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_shorturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_by',
        ),
    ]
