# Generated by Django 6.0.3 on 2026-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_shorturl_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
