# Generated by Django 3.0.3 on 2026-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20260413_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
