# Generated by Django 3.0.3 on 2026-04-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20260427_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorturl', to='links.Link'),
        ),
    ]
